version: 2
jobs:
        build:
                machine: true
                steps:
                        - add_ssh_keys:
                                fingerprints:
                                        - "e6:df:cd:0d:c2:09:ca:4c:bf:f0:21:60:a8:66:ed:33"
                        - checkout
                        - run: echo $DOCKER_USER
                          #                        - run: docker login -u $DOCKER_USER
                        - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
                        - run: docker build -t circleci/hola-docker:$CIRCLE_SHA1 .
                        - run: docker push circleci/hola-docker:$CIRCLE_SHA1
                        - run: ssh -o StrictHostKeyChecking=no ec2-user@18.188.217.61 "sudo bin/bash /home/ec2-user/deploy.sh $CIRCLE_SHA1"
